import { StyleSheet } from "react-native";
import { Colors } from "@/shared/constants/color";

export const volunteersStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  searchRow: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 44,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: Colors.textPrimary,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  statChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  statDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  statChipText: {
    fontSize: 12,
    color: Colors.textPrimary,
    fontWeight: "600" as const,
  },
  list: { flex: 1 },
  listContent: { paddingHorizontal: 20 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 14,
    marginBottom: 8,
    gap: 12,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700" as const,
  },
  cardInfo: { flex: 1, gap: 4 },
  cardName: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: Colors.textPrimary,
    letterSpacing: -0.2,
  },
  tagRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  roleTag: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  roleTagText: {
    fontSize: 10,
    fontWeight: "600" as const,
  },
  skillText: {
    fontSize: 12,
    color: Colors.textTertiary,
  },
  assignedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  assignedText: {
    fontSize: 12,
    color: Colors.textTertiary,
  },
  cardRight: {
    alignItems: "center",
    gap: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  bottomSheet: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.border,
    alignSelf: "center",
    marginBottom: 16,
  },
  closeBtn: {
    position: "absolute",
    top: 20,
    right: 20,
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: Colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetProfile: {
    alignItems: "center",
    marginBottom: 20,
  },
  sheetAvatar: {
    width: 64,
    height: 64,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  sheetAvatarText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "700" as const,
  },
  sheetName: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
    letterSpacing: -0.3,
  },
  sheetDivider: {
    height: 1,
    backgroundColor: Colors.borderLight,
    marginBottom: 16,
  },
  sheetDetail: { gap: 14 },
  sheetDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sheetDetailLabel: {
    fontSize: 14,
    color: Colors.textSecondary,
    flex: 1,
  },
  sheetDetailValue: {
    fontSize: 14,
    color: Colors.textPrimary,
    fontWeight: "500" as const,
  },
});
