import { StyleSheet } from "react-native";
import { Colors } from "@/shared/constants/color";

export const profileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  topBg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 180,
    backgroundColor: Colors.primary,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 20 },
  profileCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 22,
    alignItems: "center",
    marginBottom: 10,
  },
  avatarSection: {
    position: "relative",
    marginBottom: 12,
  },
  orgAvatar: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  orgAvatarText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "700" as const,
  },
  verifiedBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: Colors.secondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Colors.surface,
  },
  orgName: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
    marginBottom: 1,
  },
  orgFullName: {
    fontSize: 13,
    fontWeight: "500" as const,
    color: Colors.textSecondary,
    marginBottom: 3,
  },
  orgReg: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginBottom: 14,
  },
  contactList: {
    alignSelf: "stretch",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingTop: 14,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contactText: {
    fontSize: 13,
    color: Colors.textSecondary,
    flex: 1,
  },
  impactRow: {
    flexDirection: "row",
    backgroundColor: Colors.surface,
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 22,
  },
  impactItem: {
    flex: 1,
    alignItems: "center",
  },
  impactValue: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: Colors.textPrimary,
    letterSpacing: -0.3,
  },
  impactLabel: {
    fontSize: 11,
    color: Colors.textTertiary,
    marginTop: 2,
  },
  impactDivider: {
    width: 1,
    backgroundColor: Colors.borderLight,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: Colors.textTertiary,
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
    marginBottom: 8,
    paddingLeft: 4,
  },
  settingsCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    marginBottom: 22,
    overflow: "hidden",
  },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 13,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  settingsRowLast: {
    borderBottomWidth: 0,
  },
  settingsIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsTextWrap: { flex: 1 },
  settingsLabel: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: Colors.textPrimary,
  },
  logoutText: {
    color: Colors.error,
  },
  settingsSub: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginTop: 1,
  },
  footer: {
    textAlign: "center",
    fontSize: 11,
    color: Colors.textTertiary,
    marginBottom: 8,
  },
});
